### ISSUE TITLE
( I know I show up as a issue a lot) Error while build OpenSSL

### ISSUE THREAD

**Issue by SummeryLavaRain** [SideStore/sidestore_downloader#2]
> 
> cargo build 
>    Compiling libc v0.2.137
>    Compiling cfg-if v1.0.0
>    Compiling memchr v2.5.0
>    Compiling typenum v1.15.0
>    Compiling version_check v0.9.4
>    Compiling proc-macro2 v1.0.47
>    Compiling quote v1.0.21
>    Compiling unicode-ident v1.0.5
>    Compiling generic-array v0.14.6
>    Compiling bitflags v1.3.2
>    Compiling glob v0.3.0
>    Compiling lazy_static v1.4.0
>    Compiling pkg-config v0.3.26
>    Compiling unicode-width v0.1.10
>    Compiling jobserver v0.1.25
>    Compiling clang-sys v1.4.0
>    Compiling cc v1.0.76
>    Compiling log v0.4.17
>    Compiling atty v0.2.14
>    Compiling aho-corasick v0.7.19
>    Compiling minimal-lexical v0.2.1
>    Compiling regex-syntax v0.6.28
>    Compiling nom v7.1.1
>    Compiling textwrap v0.11.0
>    Compiling getrandom v0.2.8
>    Compiling libloading v0.7.4
>    Compiling humantime v2.1.0
>    Compiling vec_map v0.8.2
>    Compiling termcolor v1.1.3
>    Compiling strsim v0.8.0
>    Compiling bindgen v0.59.2
>    Compiling ansi_term v0.12.1
>    Compiling either v1.8.0
>    Compiling clap v2.34.0
>    Compiling rand_core v0.6.4
>    Compiling which v4.3.0
>    Compiling regex v1.7.0
>    Compiling rustc-hash v1.1.0
>    Compiling cexpr v0.6.0
>    Compiling lazycell v1.3.0
>    Compiling peeking_take_while v0.1.2
>    Compiling shlex v1.1.0
>    Compiling core-foundation-sys v0.8.3
>    Compiling subtle v2.4.1
>    Compiling zstd-sys v2.0.1+zstd.1.5.2
>    Compiling env_logger v0.9.3
>    Compiling block-buffer v0.10.3
>    Compiling crypto-common v0.1.6
>    Compiling autotools v0.2.5
>    Compiling openssl-src v111.24.0+1.1.1s
>    Compiling autocfg v1.1.0
>    Compiling digest v0.10.5
>    Compiling openssl-sys v0.9.77
>    Compiling tinyvec_macros v0.1.0
>    Compiling cpufeatures v0.2.5
>    Compiling syn v1.0.103
>    Compiling tinyvec v1.6.0
>    Compiling bzip2-sys v0.1.11+1.0.8
>    Compiling fastrand v1.8.0
>    Compiling ppv-lite86 v0.2.17
>    Compiling crc32fast v1.3.2
>    Compiling remove_dir_all v0.5.3
>    Compiling zstd-safe v5.0.2+zstd.1.5.2
>    Compiling tempfile v3.3.0
>    Compiling rand_chacha v0.3.1
>    Compiling unicode-normalization v0.1.22
>    Compiling core-foundation v0.9.3
> error: failed to run custom build command for `openssl-sys v0.9.77`
> 
> Caused by:
>   process didn't exit successfully: `/Users/***/Downloads/sdm/target/debug/build/openssl-sys-b4403c99004ac134/build-script-main` (exit status: 101)
>   --- stdout
>   cargo:rustc-cfg=const_fn
>   cargo:rustc-cfg=openssl
>   cargo:rerun-if-env-changed=X86_64_APPLE_DARWIN_OPENSSL_NO_VENDOR
>   X86_64_APPLE_DARWIN_OPENSSL_NO_VENDOR unset
>   cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
>   OPENSSL_NO_VENDOR unset
>   cargo:rerun-if-env-changed=CC_x86_64-apple-darwin
>   CC_x86_64-apple-darwin = None
>   cargo:rerun-if-env-changed=CC_x86_64_apple_darwin
>   CC_x86_64_apple_darwin = None
>   cargo:rerun-if-env-changed=HOST_CC
>   HOST_CC = None
>   cargo:rerun-if-env-changed=CC
>   CC = None
>   cargo:rerun-if-env-changed=CFLAGS_x86_64-apple-darwin
>   CFLAGS_x86_64-apple-darwin = None
>   cargo:rerun-if-env-changed=CFLAGS_x86_64_apple_darwin
>   CFLAGS_x86_64_apple_darwin = None
>   cargo:rerun-if-env-changed=HOST_CFLAGS
>   HOST_CFLAGS = None
>   cargo:rerun-if-env-changed=CFLAGS
>   CFLAGS = None
>   cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
>   CRATE_CC_NO_DEFAULTS = None
>   DEBUG = Some("true")
>   CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2,sse3,ssse3")
>   running "perl" "./Configure" "--prefix=/Users/***/Downloads/sdm/target/debug/build/openssl-sys-4168a36a901c8456/out/openssl-build/install" "--openssldir=/usr/local/ssl" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "darwin64-x86_64-cc" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64"
>   Configuring OpenSSL version 1.1.1s (0x1010113fL) for darwin64-x86_64-cc
>   Using os-specific seed configuration
>   Creating configdata.pm
>   Creating Makefile
> 
>   **********************************************************************
>   ***                                                                ***
>   ***   OpenSSL has been successfully configured                     ***
>   ***                                                                ***
>   ***   If you encounter a problem while building, please open an    ***
>   ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
>   ***   and include the output from the following command:           ***
>   ***                                                                ***
>   ***       perl configdata.pm --dump                                ***
>   ***                                                                ***
>   ***   (If you are new to OpenSSL, you might want to consult the    ***
>   ***   'Troubleshooting' section in the INSTALL file first)         ***
>   ***                                                                ***
>   **********************************************************************
>   running "make" "depend"
>   running "make" "build_libs"
>   perl "-I." -Mconfigdata "util/dofile.pl" \
>   	    "-oMakefile" include/crypto/bn_conf.h.in > include/crypto/bn_conf.h
>   perl "-I." -Mconfigdata "util/dofile.pl" \
>   	    "-oMakefile" include/crypto/dso_conf.h.in > include/crypto/dso_conf.h
>   perl "-I." -Mconfigdata "util/dofile.pl" \
>   	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
>   /Applications/Dev Tools/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Dev Tools/Xcode.app/Contents/Developer/usr/bin/make _build_libs
> 
>   --- stderr
>   /bin/sh: /Applications/Dev: No such file or directory
>   make: *** [build_libs] Error 127
>   thread 'main' panicked at '
> 
> 
>   Error building OpenSSL:
>       Command: "make" "build_libs"
>       Exit status: exit status: 2

**Comment by jkcoxson** [comment]
You have a space in ``Dev Tools``

**Comment by SummeryLavaRain** [comment]
> You have a space in ``Dev Tools``

lamo that would do it, thank you
