### ISSUE TITLE
[Bug] Inputting a local ipv6 ip for device results in error then close

### ISSUE THREAD

**Issue by Neptune1190** [SideStore/sidestore_downloader#3]
Inputting a ipv6 local ip causes an error about ipv4,selecting dont verify mobile pairing bypasses this

**Comment by Spidy123222** [comment]
It only accepts local ipv4 addresses which all devices should have still in 2022

**Comment by Neptune1190** [comment]
none of mine do,probably cuz my isp rolled out ipv6 for most devices by now

**Comment by jkcoxson** [comment]
Having IPv4 has nothing to do with your ISP. Your device has a local IP specific to your NAT, and the chances of your router choosing IPv6 for your NAT is slim. To find your IP, go into WiFi settings, press the (i) and scroll down.

**Comment by Spidy123222** [comment]
> none of mine do,probably cuz my isp rolled out ipv6 for most devices by now

Hm interesting I was sure local IPv4 is provided by the router. So in your WiFi you don't have IPv4 section. This one is mine for example. ![image](https://user-images.githubusercontent.com/64176728/203645247-a032c7c3-bb38-49ae-b23c-5d897af3e496.jpeg)

**Comment by jkcoxson** [comment]
I've added support for IPv6 anyways
