### ISSUE TITLE
![0DA4BD5B-4667-42CA-8D5D-484D3DE68CA3](https://user-images.githubusercontent.com/11569116/227698239-4dd204a6-54fe-4380-ae5e-7baaa382f80e.png)

### ISSUE THREAD

**Issue by BAS27-BKK** [SideStore/sidestore_downloader#7]
![0DA4BD5B-4667-42CA-8D5D-484D3DE68CA3](https://user-images.githubusercontent.com/11569116/227698239-4dd204a6-54fe-4380-ae5e-7baaa382f80e.png)

_Originally posted by @likereadboy in https://github.com/SideStore/SideStore/issues/320#issuecomment-1483729920_

**Comment by Spidy123222** [comment]
Unrelated
